apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: biddr-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: node-app-pod
    app: biddr-app